### PR TITLE
Add PyLadiesCon 2023

### PR DESCRIPTION
**Pull request by mmuman**
No schedule yet.

### CODE REVIEW

**Comment by Wilm0r** [comment]
(Hm or is Draft not the same as WiP?)

**Comment by mmuman** [comment]
I think I missclicked, and couldn't find how to switch to a draft.

**Comment by Wilm0r** [comment]
Still missing?

**Comment by mmuman** [comment]
Checked yesterday, there's some highlights on pretalx but no full schedule yet.

**Comment by mmuman** [comment]
I seem to have a weird issue with the times on my old version here. Part of the APAC track actually happen after all the other tracks on the grid, unlike on the official schedule. Could you check on a more recent version?

Screenshot_2023-11-21-15-10-20

**Comment by Wilm0r** [comment]
This is what I get for Friday: 
image

Then Saturday: 
image

Times shown are US/East. Does look different from your screenshot, are you using that ancient a Giggity version though? :(

**Comment by mmuman** [comment]
Well, Android 4… Ok then I suppose :-)

**Comment by Wilm0r** [comment]
I'm impressed a device that old still works though! That must be over 10y by now...

**Comment by mmuman** [comment]
Well I have 40y old computers that still work…

**Pull request merged**
