### PR TITLE
Create hacking-in-parallel-2022.json

### PR DESCRIPTION
**Pull request by qwaxys**

### CODE REVIEW

**Comment by Wilm0r** [comment]
Whoops how do I pick between this one and #240..

**Comment by mmuman** [comment]
Eh, LOL, whichever, cool that someone else takes the charge :-D

**Comment by qwaxys** [comment]
I guess you can just pick one xD
Once the rooms are finalized and I've got a reply on the square png I'll update wichever one it is anyway :P

**Comment by qwaxys** [comment]
@mmuman closing this one so yours can be added.
Would you be okay updating the name with slashes in the beginning and end like in the pretalx XML?
///Hacking in Parallel 2022/// seems to match the <title> more.

**Comment by mmuman** [comment]
Thanks @qwaxys for the effort !

**Pull request closed without merging**
