### PR TITLE
Add FOSSY 2023 in Portland, OR

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by EdwardBetts** [comment]
Is there anything else I need to do to get FOSSY into giggity?

**Comment by Wilm0r** [comment]
Nothing at all other than to ping me apparently, sorry for missing this one so far!!

**Comment by EdwardBetts** [comment]
I messed this up. I pointed to a schedule file that is in JSON format. I've submitted a new pull request to fix it: #282

**Comment by Wilm0r** [comment]
Heh, oops yes, the validator won't catch that yet, I've been trying to get that  Java stuff to run outside Android, but it's messy. :(

I wonder what that JSON format is.. looks trivial but not worth implementing support for of course unless it's common.

.ics stinks but so be it then. :)

**Pull request merged**
