### PR TITLE
Adding FOSSASIA 2016 event schedule

### PR DESCRIPTION
**Pull request by heysadboy**
Please add FOSSASIA 2016 event schedule.

- I have added the details in the menu.json. 
- I tried to build the app on Android Studio and there were few things came in way so fixing them also. 
- Updating the build version to 25.

Do tell if I need to update anything. When I add the .ics link manually the events shows up but doing I don't see it while emulating.

### CODE REVIEW

**Comment by Wilm0r** [comment]
Thank you - yes, all those things. :-)

Note that https://github.com/Wilm0r/giggity has some instructions on much simpler testing of new entry additions. No Android Studio (or really any kind of compiling at all) required.

**Comment by heysadboy** [comment]
@Wilm0r Thank you for looking up. When I test it by entering the iCal in the app, it is able to fetch the data and show sessions but testing it by adding it in menu.json and compiling it on device made no changes. 

I also emailed you the raw data for our event, I think that is also another option in readme.

**Comment by Wilm0r** [comment]
Ah, oops yes, had not noticed the attachment on your e-mail yet!

So .ics is the least preferred file format, Pentabarf XML files are much better, but probably you don't have much of a choice in that?

**Comment by heysadboy** [comment]
@Wilm0r Yes we do have but the data is not fetched from pentabarf and .xcs  so I was only left with .ics.
See the links below

http://open-event-dev.herokuapp.com/e/906f86d6/schedule/calendar.ics

http://open-event-dev.herokuapp.com/e/906f86d6/schedule/calendar.xcs

http://open-event-dev.herokuapp.com/e/906f86d6/schedule/pentabarf.xml

Do tell me if they are working fine. I also wanted to know if another alternative pentabarf could work if the above one is not working.

https://raw.githubusercontent.com/heysadboy/Giggity-Parser/master/Parser/sample.xml

**Comment by heysadboy** [comment]
This pentabarf link works when I add it through the app. I'll mail you the updated JSON format.

https://raw.githubusercontent.com/heysadboy/Giggity-Parser/master/Parser/sample.xml

**Comment by heysadboy** [comment]
@Wilm0r I am closing this pull request due to unwanted changes. I'll send a new one.

**Pull request closed without merging**
