### PR TITLE
Add IETF121

### PR DESCRIPTION
**Pull request by chrysn**
It's in 2 weeks time, so not sure if that makes sense still, or whether I'd better keep the file somewhere else and disseminate through QR codes.

### CODE REVIEW

**Comment by chrysn** [comment]
The link I've fixing, also the version number (not sure I got it right, just followed the bot's directions).

The Refresh is odd: I specifically did check that the server does send a 304 on ETag match. (I didn't check for date based verifciation, but always found ETag to be more widespread and reliable anyway). I'm removing this, but we do have last minute changes, so I'd prefer to put it back in.

**Comment by Wilm0r** [comment]
Feel free to put the low refresh timeout back then, as long as the server is fast. :) In fact new versions of Giggity have a better HTTP fetcher that should send ETag headers, pretty sure I've released that a while ago already. So it's just the CI that is a little behind on facts.

2w is plenty notice when I'm (able to) pay(ing) attention to this queue BTW, np. Once submitted this bit will appear in ggt.gaa.st/menu.json ~instantly and Giggity loads that file about once a day or immediately if you swipe down to refresh in the main screen.

(And ahh, IETF in Dublin... I never had it that close back when I lived there and still had an RFC to publish.. :) )

**Comment by chrysn** [comment]
Updated as you suggested -- the 2 weeks became 2 days because I missed this, but as you said, it's going out fast.

**Comment by Wilm0r** [comment]
D'oh, yep forgot it too. Merging.

**Pull request merged**
