### PR TITLE
Add PyCon FR 2019

### PR DESCRIPTION
**Pull request by mmuman**
Unable to test due to SSL error on Android 4 though.

### CODE REVIEW

**Comment by Wilm0r** [comment]
Hah @ Travis error. Guess it's running in a US timezone. I'll look into that, ignore it.

**Comment by Wilm0r** [comment]
Also, out of curiosity, what Android 4 + TLS error is that? Sounds bad..

**Comment by mmuman** [comment]
Unsupported cypher I suppose, and HTTP redirects anyway…

**Comment by Wilm0r** [comment]
> Hah @ Travis error. Guess it's running in a US timezone. I'll look into that, ignore it.

Hmm no it runs in UTC so it's not completely lying. Maybe I'll add some tolerance to it.

**Pull request merged**
