### PR TITLE
Add Kielux 2021 / LPD21.2 (online events)

### PR DESCRIPTION
**Pull request by Moini**
Hi @Wilm0r !

Kielux will start soon! This year's online event features 22 talks, 10 workshops and a Software Freedom Breakfast.

I've added our ics file links to the repository.

Greetings from Kiel!

### CODE REVIEW

**Comment by Moini** [comment]
@Wilm0r Our event starts on September 16th, would it be possible to merge well before that, so an update could also be pushed to f-droid on time?

**Comment by Wilm0r** [comment]
Darn, my apologies. I started looking at this then realised the CI once again broke quietly. From your iterations I am guessing that you ran the test locally and it succeeded?

**Comment by Wilm0r** [comment]
I guess it is. I've switched over to Github Actions now, but that won't take effect on existing PR's of course. :-(

Note that no F-Droid release is needed, Giggity fetches updates from https://ggt.gaa.st/menu.json once a day.

**Comment by Moini** [comment]
Thank you very much, @Wilm0r ! 

I've actually just re-used the files I've submitted last year, and swapped a few numbers, while being so tired that I forgot a couple of them each time, so had to make multiple commits...

Tested it in Giggity today, and it works :)

**Pull request merged**
