### PR TITLE
Add FOSDEM 2018

### PR DESCRIPTION
**Pull request by mmuman**
Same as previous year, just added a link to the stands.

### CODE REVIEW

**Comment by Wilm0r** [comment]
Thanks, yeah, funnily I was working on this a few hours before you sent in this PR already :-) But noticed that the info booklet on the FOSDEM site is still last year's. :-(

I have vague memories of refreshing of metadata not working reliably so I need to check that first and obviously fix it, in the meantime trying to avoid getting partially stale data in the seed...

**Comment by mmuman** [comment]
I asked on twitter & IRC, let's see…

**Comment by Wilm0r** [comment]
Confirmed that the refresh does work as it should, so I've pushed this out now. Pfew. :-)

**Comment by Wilm0r** [comment]
FWIW the booklet appeared and is added in https://github.com/Wilm0r/giggity/commit/76ed9e9feb8ea67d67adc3fa5c1ef1faaef87591

Still wondering whether I'm going to add support for room availability status info at the last moment https://api.fosdem.org/roomstatus/v1/listrooms

**Pull request closed without merging**
