### PR TITLE
add basic hackmas castle 24 event

### PR DESCRIPTION
**Pull request by ruru4143**

### CODE REVIEW

**Comment by ruru4143** [comment]
actions fails but doesn't provide an error. 
I checked it via https://jsonlint.com

**Comment by Wilm0r** [comment]
Weird that the comment is empty yes... :-/ but see https://github.com/Wilm0r/giggity/actions/runs/10164485309/job/28109952792?pr=366 for the actual error

**Comment by ruru4143** [comment]
for me, this is ready to merge @Wilm0r

**Comment by ruru4143** [comment]
i will do another pull request as soon c3nav is working.

**Comment by Wilm0r** [comment]
Thank you! BTW I see only 3 or 4 items in the schedule, shouldn't it be a lot more?

**Comment by Wilm0r** [comment]
Wow OK, that's very last minute :)

Sorry, should've asked this earlier, and I'll pay attention to this PR today so that we can get it submitted, but ... the URL parameters, are they really really necessary? Only asking because if you want to delete them later, Giggity uses the full URL as the primary key so doing so would result in 2 hackmas menu entries with separate selections and all in all terrible UX. I've started working out a fix but it's not there yet... :(

FWIW if I fetch the same URL without parameters I seem to get the exact same results at least, so I'm tempted to cut it off.

**Comment by ruru4143** [comment]
The limit is necessary, because the default limit is something around 200-300. We won't change the parameters anymore tho.

**Comment by ruru4143** [comment]
I really don't understand how these versionnumbers work...

**Comment by ruru4143** [comment]
ok now i get it, it's current date + a number which must be growing

**Comment by Wilm0r** [comment]
Yeah, sorry about that, I should remove version numbers from these src files too some day. Much of Giggity is 15yo, not all design decisions are great. :)

**Comment by ruru4143** [comment]
Hahaha, sounds like it should get a rewrite at some point. Thanks for supporting this app for so long!

**Pull request merged**
