### PR TITLE
Add State of the Map Europe 2024

### PR DESCRIPTION
**Pull request by Zverik**
This is basically the same as last year. Could you please merge it before 19th? Sorry for being so close to the conference dates.

### CODE REVIEW

**Comment by fortysixandtwo** [comment]
style nit: these two commits should be squashed ;)

**Comment by Zverik** [comment]
okay

**Comment by Wilm0r** [comment]
Sorry, missed the start :(

**Comment by Wilm0r** [comment]
Wish I noticed the tight timing earlier. BTW did you see that you can include ggt.gaa.st links/QRs that people can scan which will auto-store the same schedule and metadata on the phone?

**Comment by Zverik** [comment]
Hey it's fine, there are backup instructions at https://sotm.osmz.ru/sotmeu24.html :) Thanks for merging!

**Comment by Wilm0r** [comment]
Ah, nicely done :) So to "spice up" the `ggt.gaa.st` link a little bit you can use this trick:

```
wilmer@ruby:~/android/deoxide$ tools/ggt.sh menu/sotm_eu_2024.json 
https://ggt.gaa.st#url=https://sotm.osmz.ru/sotmeu24.xml&json=H4sIAAAAAAACA12PMWvDMBCF9_wKcXNiyyLURXvHTh0yhBCu5IxFLMnoTmmI8X-vlC6h43v3-PhugRsldjGANdrsdd-9ab2FnCawMIrMbNuWo_gmsn80KT8DZbNv7n6CLYiTicr2S1BIxUHJSOoTZ_WRU5xJVWqZsWCSMqtxp_td915KCpeXynRPnKdHDJX4B2gPmBh_yinRkIjHswtC6YZFsDfV1ZPgBQXBLjC5cGWwx-X_B9UuDsXN49xQbl_MD_TNTgjW07pufgEzVDsFEAEAAA==
```

That deeplink will auto import the json metadata as well, whether from a QR (admittedly a very large one) or deeplink in the mobile browser.

**Comment by Zverik** [comment]
Oh, nice to know, thanks!

**Pull request merged**
