### PR TITLE
Add Installfest 2022

### PR DESCRIPTION
**Pull request by jakubjancicka**
Hello, I would like to ask for add installfest 2022 to menu. Thnak you

### CODE REVIEW

**Comment by jakubjancicka** [comment]
The check has failed because of a link redirect - it will be fixed a week before a conference when we write down info for attendees.

**Comment by Wilm0r** [comment]
Note the other warning about missing timezone info.

**Comment by jakubjancicka** [comment]
Oh sorry, I've missed this. It's fixed now.

**Comment by Wilm0r** [comment]
Sorry for the delay!

**Pull request merged**
