### PR TITLE
Linux event tuebix 2018

### PR DESCRIPTION
**Pull request by christophprokop**
now with tabs :)

### CODE REVIEW

**Comment by Wilm0r** [comment]
Hrmm, thank you for reminding me to add a new test to the CI when I have 
a chance (-: mind moving this to the bottom to keep the file 
chronological?

(though now I wonder, should it be sorted by conf start date? It may 
just be sorted by addition date ATM which is harder to test properly 
maybe)

**Comment by christophprokop** [comment]
thx for your fast response!
now at the bottom of the file :)

**Comment by christophprokop** [comment]
our linux event is on the day after tomorrow, so merging today would be cool ;)

**Comment by Wilm0r** [comment]
Merged ... but it looks like the &# escaping of ü was unnecessary and caused the meny entry to look ugly until the file is actually loaded (at which point the menu.json title gets overwritten with data from your schedule).

**Pull request merged**
