### PR TITLE
Add Hacking in Parallel (Berlin) 2022

### PR DESCRIPTION
**Pull request by mmuman**

### CODE REVIEW

**Comment by mmuman** [comment]
PNG icon isn't available yet, let's see if they fix it.

**Comment by mmuman** [comment]
I removed the icon for now, we can always add it back.

**Comment by Wilm0r** [comment]
Whoops how do I pick between this one and #241..

**Comment by mmuman** [comment]
I also added the 2 other links from #241 since I didn't even notice there was a wiki link on the website.

**Comment by qwaxys** [comment]
> Whoops how do I pick between this one and #241..

Resolved :)

**Comment by Wilm0r** [comment]
Urgh lost track of this again but I see it's still a week away, pfew. :)

**Pull request merged**
