### PR TITLE
Add 38C3

### PR DESCRIPTION
**Pull request by schildbach**
I left out c3nav for now.

### CODE REVIEW

**Comment by schildbach** [comment]
I also removed `refresh_interval` because:

> ERROR: Schedule 38C3 refresh_interval set below 1d while server never sends HTTP 304s

**Comment by schildbach** [comment]
@Wilm0r ready for review.

**Comment by Wilm0r** [comment]
Hrmm.... Hadn't noticed the refresh interval thing before. I should fix that check, Giggity should be better at HTTP caching now (including ETags, which are more likely to work IIRC).

CCC does probably make last minute schedule changes somewhat regularly?

**Comment by mmuman** [comment]
Oh cool, won't have to do it.
Yes there are usually many updates to the schedule…

**Comment by mmuman** [comment]
It's sad the [full schedule](https://events.ccc.de/congress/2024/hub/en/fahrplan?mode=calendar&kind=official&set=kall#now) doesn't pull from an xml…

**Pull request merged**
