### PR TITLE
add libreplanet 2020 event

### PR DESCRIPTION
**Pull request by ian-kelling**

### CODE REVIEW

**Comment by ian-kelling** [comment]
Fixed the tab+spaces issue by going with just spaces.

**Comment by Wilm0r** [comment]
Do you always ignore CI failures when you send PRs to projects?

Android doesn't (trivially) support SVG as Drawables.

**Comment by ian-kelling** [comment]
Sorry about that. Thanks for the  feedback. CI is passing now, I think all the issues are sorted.

**Comment by Wilm0r** [comment]
Excellent, thank you :-)

**Pull request merged**
