### PR TITLE
WIP: Add Pass The SALT 2019

### PR DESCRIPTION
**Pull request by mmuman**
Schedule not online yet, but the 2018 one worked.

### CODE REVIEW

**Comment by Wilm0r** [comment]
Hrmm, should I wait for this one (and the other 3) to get past WiP with merging?

**Comment by mmuman** [comment]
Yeah I'd rather test them first.

**Comment by mmuman** [comment]
Eh, schedule is now [online](https://2019.pass-the-salt.org/schedule/) but it seems they switched CfP tool this year and I can't find any xml or ics :-(

**Comment by mmuman** [comment]
Hopefully we'll get something next year…

**Pull request closed without merging**
