### PR TITLE
Add CCCamp23

### PR DESCRIPTION
**Pull request by mmuman**
Fahrplan not available yet.

### CODE REVIEW

**Comment by Wilm0r** [comment]
Wow and it's still not there apparently?

**Comment by dos1** [comment]
It has just been published today, the URL is https://pretalx.c3voc.de/camp2023/schedule/export/schedule.xml

**Comment by mmuman** [comment]
Yay!
Currently adding room locations.

**Comment by mmuman** [comment]
Seems the map doesn't have the villages yet, I'll see later if I can add them.
Tested and working.

**Comment by mmuman** [comment]
Someone on their Matrix could ask them to fix pretalx to send the HTTP 304?

**Comment by Wilm0r** [comment]
> Someone on their Matrix could ask them to fix pretalx to send the HTTP 304?

That'd definitely be nice, though I guess also not trivial.. Their server is fast and the schedule file isn't too large, so maybe I shouldn't be so overly cautious about slow conference WiFi (how big a problem is that, still?)..

Also I should have Giggity use `ETag` headers, and/or figure out whether there's a fancier HTTP fetcher for Android that understands all the caching logic already.

```
wilmer@veer:~$ wget -S -O/dev/null https://pretalx.c3voc.de/camp2023/schedule/export/schedule.xml
--2023-08-04 06:30:18--  https://pretalx.c3voc.de/camp2023/schedule/export/schedule.xml
Resolving pretalx.c3voc.de (pretalx.c3voc.de)... 2a01:a700:48d1::105, 31.172.33.105
Connecting to pretalx.c3voc.de (pretalx.c3voc.de)|2a01:a700:48d1::105|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Server: nginx
  Date: Fri, 04 Aug 2023 04:30:19 GMT
  Content-Type: text/xml
  Content-Length: 458963
  Connection: keep-alive
  ETag: 9396400fa19df71bfad8a1a8f864a6e8966d6b62
  Access-Control-Allow-Origin: *
  X-Frame-Options: DENY
  Vary: Cookie
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  Referrer-Policy: strict-origin-when-cross-origin
  Strict-Transport-Security: max-age=63072000; includeSubDomains
  Permissions-Policy: interest-cohort=()
Length: 458963 (448K) [text/xml]
Saving to: ‘/dev/null’

/dev/null                    100%[============================================>] 448.21K  1.72MB/s    in 0.3s    

2023-08-04 06:30:19 (1.72 MB/s) - ‘/dev/null’ saved [458963/458963]

wilmer@veer:~$ wget --header="If-None-Match: 9396400fa19df71bfad8a1a8f864a6e8966d6b62" -O/dev/null https://pretalx.c3voc.de/camp2023/schedule/export/schedule.xml
--2023-08-04 06:30:21--  https://pretalx.c3voc.de/camp2023/schedule/export/schedule.xml
Resolving pretalx.c3voc.de (pretalx.c3voc.de)... 2a01:a700:48d1::105, 31.172.33.105
Connecting to pretalx.c3voc.de (pretalx.c3voc.de)|2a01:a700:48d1::105|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
2023-08-04 06:30:22 ERROR 304: Not Modified.
```

**Comment by mmuman** [comment]
Ok I heard the villages should be published "soon" :-)

**Comment by Wilm0r** [comment]
In a separate huge "merged" file again?

**Comment by mmuman** [comment]
I mean on the map, it seems to be quite merged already, I wasn't sure when I created the file…

**Comment by Wilm0r** [comment]
Want to just merge with the existing refresh issue BTW? I'm playing around with Android's `HttpResponseCache` as a replacement for my old elaborate yet still incomplete (and very stale) caching mechanism, after already verifying that it *does* get a 304 on this URL on second try. (No clue why because it's TLS obviously, but I guess it'll be `ETag`..)

**Comment by mmuman** [comment]
Seems the map has been updated…
And of course the schedule also has been updated with new room names…

**Comment by mmuman** [comment]
My old tablet finally accepted to boot so I could test it.

**Comment by mmuman** [comment]
Is the caching issue still a problem?

**Comment by Wilm0r** [comment]
(Caching still a problem but meh, so be it. I'm reworking `Fetcher.java` right now to use `HttpResponseCache` instead which does HTTP caching more properly including use of ETags, that'll help in the future. I'll see how much caching/expiry logic to even keep inside Giggity itself by then, it's currently a slight layering violation.)

**Pull request merged**
