### PR TITLE
Add OSSEU+Linux Embedded Conference Europe

### PR DESCRIPTION
**Pull request by mmuman**
Combined shedule.

Stupid sched.com puts a "X-WR-CALDESC:Event Calendar" in the ICS so the conf gets renamed…

### CODE REVIEW

**Comment by mmuman** [comment]
Error 500… odd, works here…

**Comment by Wilm0r** [comment]
Yes, that is strange. I can fetch it fine as well with at least wget.
Running the CI script locally also does not reproduce?

**Comment by mmuman** [comment]
Ah, same here… I don't have the reflex to run it everytime. Maybe the User Agent it uses is blacklisted or something?

**Comment by Wilm0r** [comment]
The urllib3 default appears to be no User-Agent: header at all and
adding one indeed seems to fix this. Weird. Guess I'll add that when I
have a chance..

**Comment by Wilm0r** [comment]
> Stupid sched.com puts a "X-WR-CALDESC:Event Calendar" in the ICS so the conf gets renamed…

That's fixed in the quagmire branch BTW, at last. But yes that's not going to help current users. :-( It's not really release-ready yet and it will drop API <6.0 (23?)... Don't really fancy a backporting exercise though. :-/

**Comment by Wilm0r** [comment]
Oh drat, only now notice that the event has already started..

**Pull request merged**
