### PR TITLE
Add DebConf 22

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by fortysixandtwo** [comment]
Would also be nice to include the icon metadata:

https://debconf22.debconf.org/static/img/dc22-logo.c16625389b0f.svg

**Comment by EdwardBetts** [comment]
@fortysixandtwo I don't think giggity supports SVG icons, none of the other conferences in the menu have SVG icons. The ./tools/menu-ci.py script complains if I try adding an SVG icon.

**Comment by fortysixandtwo** [comment]
Thanks for pointing it out,

I've proposed adding the icon rendered as png upstream:

https://salsa.debian.org/debconf-team/public/websites/dc22/-/merge_requests/74

If this get's accepted I'll get back to you

**Comment by fortysixandtwo** [comment]
URL of png is here: https://salsa.debian.org/debconf-team/public/data/dc22/-/raw/main/artwork/DebConfOfficialLogo.png?inline=false

**Comment by stefanor** [comment]
Let's merge that MR to the website - the salsa.debian.org admins don't like people using it as a webhost / CDN.

**Comment by stefanor** [comment]
Here: https://debconf22.debconf.org/static/img/dc22-logo.741bbe09dda7.png

**Pull request merged**
