### PR TITLE
Add JdLL 2023

### PR DESCRIPTION
**Pull request by sparunakian**
Hi! This MR adds the 2023 edition of the JdLL event.

### CODE REVIEW

**Comment by sparunakian** [comment]
It seems that the failure of the second batch of checks is not due do this MR.

**Comment by Wilm0r** [comment]
Yep sorry, really need to fix that :( Trashy github permissions model..

**Comment by mmuman** [comment]
Oh cool, I was just noticing I didn't do it this year, then I saw this when pulling. Thanks!

**Comment by sparunakian** [comment]
Thank you for merge and thank you for this project!

**Pull request merged**
