### PR TITLE
Create newline2023.json

### PR DESCRIPTION
**Pull request by qwaxys**

### CODE REVIEW

**Comment by Wilm0r** [comment]
Sorry, this is new code trying to post a "all OK!" comment that worked when I tested it, but apparently there are permissions issues when the PR is someone else's. I'll try to fix it within the next day or so, would you be willing to help me verify the fix later? (Likely by doing a no-op new commit+push)

**Comment by qwaxys** [comment]
Happy to help, I could add a link in the json later to the event? This should trigger the script again.
Mind manually passing this one trough? I would like to mention our schedule is available on Giggity 😅

**Comment by Wilm0r** [comment]
Hah yes you're right, let's use a new PR for that. I don't have time to figure out these "personal access tokens" right now :(

**Comment by qwaxys** [comment]
Thanks!
Feel free to ping me when you need testing :)

**Comment by Wilm0r** [comment]
OK, I *think* it's fixed, if you have a moment to check it out I'd be grateful :) No clue how to test this myself other than creating a throwaway Github account..

**Comment by qwaxys** [comment]
I'll do an edit?

**Pull request merged**
