### PR TITLE
Add GNU Radio Conference 2023 in Tempe, Arizona, USA

### PR DESCRIPTION
**Pull request by marcusmueller**
Noticed a bit late this was an option; would be very grateful if merged!

### CODE REVIEW

**Comment by marcusmueller** [comment]
changed that, force-pushed

**Comment by marcusmueller** [comment]
As a fellow maintainer, I hate to do this, but:
Ping @Wilm0r , as this gets time-critical, sadly, even starts next Tuesday.

**Comment by Wilm0r** [comment]
No problem wrt the ping, thanks in fact! Don't know how I missed this one :( But this is why I am looking into (semi) auto approval on PRs with green CI..

**Comment by marcusmueller** [comment]
No, thank *you*. Should we happen to run across each other (FOSDEM'24?), remind you that I owe you a preferred beverage :D

**Comment by Wilm0r** [comment]
Hah ok :) Will be hard to go to FOSDEM while I still live in the wrong continent for a while, but ... one day.

**Pull request merged**
