### PR TITLE
Add JDLL 2019

### PR DESCRIPTION
**Pull request by mmuman**
Not sure the ICS will work again, time will tell.

### CODE REVIEW

**Comment by mmuman** [comment]
This year they switched to Pretalx for the CfP, which is able to generate a pentabarf compatible XML file, so hopefully I'll get an URL to test soon.

**Comment by mmuman** [comment]
Hmm, added the Mastodon avatar as icon, not transparent but it's square at least. Can't really test it as it never worked on my Android 4 tablet.
Also their SSL setup makes Android 4 freak out, so I had to copy the xml around for testing.

**Comment by mmuman** [comment]
ping :-)

**Comment by Wilm0r** [comment]
Sorry for the delay! Missed that this wasn't draft anymore :-(

**Comment by mmuman** [comment]
Thanks!

**Pull request merged**
