### PR TITLE
Add LibrePlanet 2018

### PR DESCRIPTION
**Pull request by mmuman**
Work in progress: URL is for 2017 schedule for testing. DO NOT MERGE YET.

### CODE REVIEW

**Comment by mmuman** [comment]
Note there is a 100x100 png available, but it seems to be with the 2017 logo.
I suppose the URL for the 2018 ICS should be similar.

**Comment by mmuman** [comment]
Just created a PR for their schedule generator script to add the X-WR-CALNAME:
https://notabug.org/rsd/lpschedule-generator/pulls/10

**Comment by Wilm0r** [comment]
This was far away but is finally coming close :-) Want to sync/update?

**Comment by mmuman** [comment]
I checked the website several times but didn't see the program yet. I'll remind them.

**Comment by mmuman** [comment]
The program is finally online but the ICS isn't yet. I'll check back in some hours.

**Comment by mmuman** [comment]
Just got the schedule URL and tested, works for me.™

I have the JDLL to add as well, do you want a single PR along with FOSSASIA ?

**Comment by mmuman** [comment]
Looks like the PR is too old to trigger travis automatically despite the forced push…

**Comment by ian-kelling** [comment]
@Wilm0r sorry this is rather late, but afaik, it's ready and the event is this weekend so I'd be grateful if you can merge this soon. Thanks.

**Comment by Wilm0r** [comment]
I'd do this now, but .... .ics 404s?

The requested URL /2018/schedule.ics was not found on this server.

**Comment by mmuman** [comment]
It worked the other day… did you remove it or something??

**Comment by ian-kelling** [comment]
i'm fixing it now

**Comment by ian-kelling** [comment]
/2018/schedule.ics is back now. thanks for noticing, and pull when you get a chance.

**Comment by mmuman** [comment]
Ok, just rebased.

**Comment by Wilm0r** [comment]
Manually pushed because even without a serial# conflict Github can't cope. \o/

**Comment by mmuman** [comment]
Thanks.
It shouldn't cause that many trouble merging json with those many identical lines separating chunks… maybe we could try adding an empty line between each conference?

**Comment by Wilm0r** [comment]
Maybe that.. or maybe I should look into having separate small files in VCS and automatically host a merged copy elsewhere.

**Comment by mmuman** [comment]
That would certainly work.

**Pull request closed without merging**
