### PR TITLE
Add Opensouthcode 2018

### PR DESCRIPTION
**Pull request by davidsf**
Add Opensouthcode 2018

### CODE REVIEW

**Comment by mmuman** [comment]
You'll want to remove the comma after the block you added, JSON doesn't like it.

**Comment by davidsf** [comment]
Ok, done.

**Comment by davidsf** [comment]
Can you please merge this PR? this event is this friday. Thanks!

**Comment by davidsf** [comment]
I have replaced the logo with a small and square one. Now all checks pass :)

**Comment by davidsf** [comment]
Hi, can this PR be merge please? Thanks !

**Comment by Wilm0r** [comment]
Very sorry, missed this while on a long and far away holiday (with added fun of my home infrastructure having gone belly up 2w ago). :-(

**Comment by davidsf** [comment]
Don't worry, my bad to open the PR too late.  Next year I will try to open early :)

Thanks a lot

**Pull request closed without merging**
