### PR TITLE
WIP: Add Paris Web 2017

### PR DESCRIPTION
**Pull request by mmuman**
DO NOT MERGE YET:
WIP: the ICS "appears to be empty" for some reason...

### CODE REVIEW

**Comment by mmuman** [comment]
Hmm conference is in two days anyway. Still, would be nice to know the why of #26 ...

**Comment by mmuman** [comment]
Ok, now we just need them to host a fixed version of the ICS.

**Comment by mmuman** [comment]
I've put a fixed version on my own website for now, I don't know if they'll have the time tonight to host it...

For the record, I've added `--json_opt utf8,pretty` to the test in my `pre-commit` hook.

**Comment by Wilm0r** [comment]
OK, and now it's already over so no point in merging? :-( Sorry about that. But did you manage to get it used by for example hosting a gzip-QR version of your json blob?

**Comment by mmuman** [comment]
Yeah I posted the QR on twitter & mastodon, not sure it was of any use. I think we can close it now. We can always dig that next year.
We should still try to add support for DURATION in ICS files.

**Pull request closed without merging**
