### PR TITLE
Add Capitole du Libre 2023

### PR DESCRIPTION
**Pull request by mmuman**

### CODE REVIEW

**Comment by mmuman** [comment]
Me, before doing the PR: … oh, must fix the timestamp in that JSON file, it's from 2 days ago…

CI: Oh, the timestamp is in the future…

🤷

**Comment by Wilm0r** [comment]
Hah! I worried that CI could be running in some US timezone, but docs day it's UTC, and indeed your comment was on Monday the 23rd at 23:45 UTC I think?

**Comment by mmuman** [comment]
Probably, we're UTC+2 here…

**Comment by Wilm0r** [comment]
I guess I could add a timezone tag in the error message, or for "comfort", maybe use Australian timezone :)

**Comment by mmuman** [comment]
It's fine as-is really.

**Pull request merged**
