### PR TITLE
Add FOSSASIA Summit 2022

### PR DESCRIPTION
**Pull request by mmuman**

### CODE REVIEW

**Comment by mmuman** [comment]
Ah, icon is JPEG…

**Comment by mmuman** [comment]
Dropped the icon.

**Comment by Wilm0r** [comment]
Hrm, yeah, so a while ago @heysadboy contributed a parser for FOSSASIA's JSON format which seemed like it was trying to become a broader standard. IIRC I've removed that code again a while ago since I couldn't see even FOSSASIA themselves still using it. :(

Sad because .ics stinks. But so be it.

And yeah, I think .jpeg icons *would* work but let's just not do it. Lack of transparency--

**Comment by mmuman** [comment]
Yeah, shame but well…

**Pull request merged**
