### PR TITLE
add CfgMgmtCamp 2019 to the event list

### PR DESCRIPTION
**Pull request by toshywoshy**
Request to add the conference Config Management Camp 2019 schedule to be listed

Signed-off-by: Toshaan Bharvani <toshaan@vantosh.com>

### CODE REVIEW

**Comment by toshywoshy** [comment]
That looks better and thanks for the suggestion of the image

**Comment by Wilm0r** [comment]
That file has the low-res logo scaled up instead of just using the 128×128 one from https://cfgmgmtcamp.eu/images/logo_name_big.png . I'm pretty sure taking just the logo (not the text) from https://cfgmgmtcamp.eu/images/logo_name_big.png would look by far the best.

**Comment by toshywoshy** [comment]
My graphical skills are not very good, so yes, I might have scaled the image too big and so not as optimally.
Does this look better https://cfgmgmtcamp.eu/images/logo_name_big.png ?

**Comment by Wilm0r** [comment]
Yes :-) I personally would have just the logo without the text as it's going to be unreadable anyway at the sizes used on screen, but okay, also up to you.

**Comment by toshywoshy** [comment]
You mean like this then https://cfgmgmtcamp.eu/images/logo_name_big.png

**Comment by Wilm0r** [comment]
Yep, that'd be my preference!

**Comment by toshywoshy** [comment]
Are we good to go, or do I need to make any more changes?

**Comment by Wilm0r** [comment]
Sorry, yes, I forgot that the URL didn't change and therefore no new commit was necessary.

**Pull request merged**
